### ISSUE TITLE
Recursive records

### ISSUE THREAD

**Issue by samtefey** [jaredramirez/rescript-json#1]
Hey, library looks great. 

Is possible to create a decoder for the following?

`type rec  t = { id: string, child: t }`

Thanks

**Comment by jaredramirez** [comment]
Hey there!

Yes, this is possible with a minor change to your type. It would need to be:
```rescript
type rec t = { id: string, child: option<t> }
```
It doesn't have to be an `option`, but the child `t` needs to be wrapped in some type that has an empty state otherwise it'd be infinitely recursive.

With the type above, you can do:
```rescript
let rec decoder: unit => Json.Decode.t<t> = () => {
  open Json.Decode
  map2(
    field("id", string),
    option(field("child", decoder())),
    ~f=(id, optChild) => { id: id, child: optChild }
  )
}
``` 

Unfortunately, the way Rescript's recursive syntax works, the recursive value has to be a function so our decoder here takes `unit`.

I think there's a possibility for using [lazy](https://rescript-lang.org/docs/manual/latest/lazy-values) here too, but that's probably a separate issue/feature.

**Comment by jaredramirez** [comment]
Closing this for now. If the above doesn't answer your question feel free to reopen.

**Comment by samtefey** [comment]
Hey, sorry for reopening this but when I try to use the above it blows the stack

**Comment by andremw** [comment]
Yeah, it blows the stack indeed.

Did any of you guys figure out another way to do this?

@samtefey @jaredramirez 

I just noticed [elm json has a lazy decoder](https://package.elm-lang.org/packages/elm/json/latest/Json-Decode#lazy). What would be necessary for us to implement it? I can try that

**Comment by andremw** [comment]
Hey, looks like I made it:

```rescript
let lazy_ = thunk => Json.Decode.andThen(succeed(), ~f=thunk)

type rec comment = {message: string, responses: array<comment>}

let rec commentDecoder: unit => Json.Decode.t<comment> = () => {
  open! Json.Decode

  succeed((msg, responses) => {message: msg, responses: responses})
  ->andMap(field("message", string))
  ->andMap(field("responses", array(lazy_(_ => commentDecoder()))))
}

// or

let rec commentDecoder: unit => Json.Decode.t<comment> = () => {
  open! Json.Decode

  map2(field("message", string), field("responses", array(lazy_(_ => commentDecoder()))), ~f=(
    message,
    responses,
  ) => {message: message, responses: responses})
}
```

Yeah, that's working. ✅
